openapi: 3.0.3
info:
  title: Webhook Example
  version: 1.0.0
paths:
  /pets:
    post:
      description: subscribes a client to receive out-of-band data
      parameters: []
      responses:
        '200':
            description: Your server should return this HTTP status code if the subscription was successful
      callbacks:
        onData:
          '{$request.query.callbackUrl}/data':
            post:
              requestBody:
                description: subscription payload
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/Pet'
              responses:
                '202':
                  description: |
                    Your server implementation should return this HTTP status code if the data was received successfully.
components:
  schemas:
    Pet:
      title: Pet
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
