openapi: 3.0.1
info:
  title: Sample API
  version: 1.0.0
components:
  schemas:
    Book:
      title: BookDto
      type: array
      items:
        $ref: '#/components/schemas/BookDetails'
    BookDetails:
        title: BookDetailsDto
        type: object
        additionalProperties:
          type: string
