openapi: 3.0.1
info:
  title: Sample API
  version: 1.0.0
components:
  schemas:
    Book:
      title: BookDto
      type: array
      items:
        oneOf:
          - type: string
            format: "unix_timestamp"
          - type: string
            format: "sample_value"
