openapi: 3.0.1
info:
  title: Sample API
  version: 1.0.0
components:
  schemas:
    Book:
      title: BookDto
      type: object
      properties:
        title:
          type: string
        author:
          type: string
        year:
          type: integer
        price:
          type: number
          format: double
