openapi: 3.1.0
info:
  title: Webhook Example
  version: 1.0.0
webhooks:
  newPet:
    post:
      description: A new pet is born, let's come and discover it in Petstore.
      requestBody:
        description: Information about a new pet in the system
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
      responses:
        "200":
          description: Return a 200 status to indicate that the data was received successfully
components:
  schemas:
    Pet:
      title: Pet
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
